
baseurl = "/"
languageCode = "en-US"
title = "Smokelyze"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[permalinks]
  post = "/:year/:slug/"

[[menu.main]]
  name = "Map"
  url = "/map/"
  weight = 1

[[menu.main]]
  name = "Resources"
  url = "#"
  weight = 2
  identifier = "resrc"

[[menu.main]]
  name = "Announcements"
  url = "/resrc/announcements/"
  weight = 1
  parent = "resrc"
  
[[menu.main]]
  name = "FAQ"
  url = "/resrc/faq/"
  weight = 2
  parent = "resrc"
  
[[menu.main]]
  name = "Data"
  url = "/resrc/data/"
  weight = 3
  parent = "resrc"

[[menu.main]]
  name = "Documents"
  url = "/resrc/documents/"
  weight = 4
  parent = "resrc"

[[menu.main]]
  name = "Links"
  url = "/resrc/links/"
  weight = 5
  parent = "resrc"

[[menu.main]]
  name = "About"
  url = "#"
  weight = 4
  identifier = "about"

[[menu.main]]
  name = "Smokelyze?"
  url = "/about/smokelyze/"
  weight = 1
  parent = "about"

[[menu.main]]
  name = "About us"
  url = "/about/about_us/"
  weight = 2
  parent = "about"

[[menu.main]]
  name = "Contact"
  url = "/about/contact/"
  weight = 3
  parent = "about"

[[menu.main]]
  name = "Terms of Use"
  url = "/about/terms-of-use/"
  weight = 4
  parent = "about"

[[menu.main]]
  name = "Privacy Policy"
  url = "/about/privacy-policy/"
  weight = 5
  parent = "about"
  
[params]
  description = "A website built through Hugo and blogdown."
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  [params.logo]
  url = "smokelyze_logo.webp"
  width = 50
  height = 50
  alt = "Logo"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = false

